#!/usr/bin/node
const fs = require('fs')
const path = require('path')
const { ArgumentParser } = require('argparse')
const { version } = require('./package.json')
const geoip = require('geoip-country')

const parser = new ArgumentParser({
  description: 'IP to country'
})

parser.add_argument('-v', '--version', { action: 'version', version })
parser.add_argument('--key', { help: 'License key', required: false })

const args = parser.parse_args()
console.log('args', args)

if (!args.key) {
  args.key = fs.readFileSync(path.join(__dirname, '.maxmind'), 'utf-8').split('\n')[0]
}

console.log('Updating GeoIP')
const start = Date.now()

geoip.updateDatabase(args.key, (err, res) => {
  if (err) {
    console.log(err)
    return process.exit(1)
  }

  console.log('- updated in', ((Date.now() - start) / 1000).toFixed(1), 'seconds')
  process.exit(0)
})
